export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS";
export const APPLY_COUPON_FAILED = "APPLY_COUPON_FAILED";
export const UNCHECKED_COUPON_SUCCESS = "UNCHECKED_COUPON_SUCCESS";
export const UNCHECKED_COUPON_FAILED = "UNCHECKED_COUPON_FAILED";
export const APPLY_COUPON_REQUEST = "APPLY_COUPON_REQUEST";
export const UNCHECKED_COUPON_REQUEST = "UNCHECKED_COUPON_REQUEST";
