export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART = "REMOVE_CART";
export const DECREASE_QUANTIRY_CART = "DECREASE_QUANTIRY_CART";
export const INCREASING_QUANTIRY_CART = "INCREASING_QUANTIRY_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
